# Generated by Django 6.0.3 on 2026-03-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('cont_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('contact_num', models.IntegerField(verbose_name='Contact Number')),
                ('email', models.CharField(default='', max_length=50)),
                ('company_type', models.CharField(max_length=50, verbose_name='Company Type')),
                ('address', models.CharField(max_length=90, verbose_name='Address Line 1')),
                ('address_2', models.CharField(max_length=90, verbose_name='Address Line 2')),
                ('landmark', models.CharField(max_length=50, verbose_name='Landmark')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pincode', models.IntegerField(verbose_name='Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('gstin_number', models.CharField(max_length=15)),
                ('address_1', models.CharField(max_length=90)),
                ('address_2', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=40)),
                ('password_1', models.CharField(max_length=40)),
                ('password_2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_type', models.CharField(max_length=50)),
                ('Invoice_num', models.CharField(blank=True, max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Dispatch_through', models.CharField(max_length=50)),
                ('Due_date', models.DateField(blank=True)),
                ('Bank', models.CharField(max_length=20)),
                ('Payment_type', models.CharField(max_length=20)),
                ('Payment_note', models.TextField(max_length=50)),
                ('T_c', models.TextField(max_length=100)),
                ('Document_note', models.TextField(max_length=100)),
                ('qrcode', models.ImageField(blank=True, default='', upload_to='')),
                ('subtotal', models.FloatField(default=0)),
                ('gst_total', models.FloatField(default=0)),
                ('discount_total', models.FloatField(default=0)),
                ('final_total', models.FloatField(default=0)),
                ('Cust_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.customerdetails')),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails')),
            ],
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='companyName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails'),
        ),
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='payment_qr/')),
                ('payment_link', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Hsn_code', models.CharField(max_length=20)),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField(default=0)),
                ('Cgst', models.IntegerField(default=0)),
                ('Sgst', models.IntegerField(default=0)),
                ('Igst', models.IntegerField(default=0)),
                ('Cess', models.IntegerField(default=0)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Invoice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.invoice_details')),
                ('companyName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails')),
            ],
        ),
    ]
