# Generated by Django 6.0.3 on 2026-03-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Total',
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisationdetails'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.invoice_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.product')),
            ],
        ),
    ]
