# Generated by Django 5.2.4 on 2026-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationdetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
