# Generated by Django 5.2.4 on 2026-04-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_organisationdetails_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='organisationdetails',
            name='password_1',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='organisationdetails',
            name='password_2',
            field=models.CharField(max_length=225),
        ),
    ]
